export const roles = {
    "sergeant first class": "",
    "sergeant": "",
    "ems supervisor": "",
    "senior specialist": "",
    "specialist": "",
    "senior paramedic": "",
    "paramedic": "",
    "student paramedic": "",
    "emt": "",
    "medical department": "",
    "ftp": "",
    "fts": "",
    "angel one": "",
    "angel one instructor": "",
    "lsmr": "",
    "doctor": "",
    "med student": "",
    "nurse": "",
    "nursing student": "",
    "therapist": "",
    "tecc": "",
    "lsmr professor": ""
}
